In [22]:
# Nativos
import random as rn
import os
import sys
import gc

#calculo
import numpy as np
import pandas as pd
import scipy

#grafico
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display
%matplotlib inline
sns.set(style="whitegrid")

#warning ignore future
import warnings
# warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings("ignore")
gc.collect()

BASE_DIR = os.path.dirname(os.getcwd())
if BASE_DIR not in sys.path: sys.path.append(BASE_DIR)

#from utils import *
#from graphs import *

SEED = 29082013
os.environ['PYTHONHASHSEED']=str(SEED)
np.random.seed(SEED)
rn.seed(SEED)

subfolder = "data"
# os.listdir(subfolder)

In [23]:
data_accidente = pd.read_excel(
    "{}/DATA_ACCIDENTE_2016_2018_HACKHATON.xlsx".format(subfolder)
)
data_accidente.head()

,ID_ACCIDENTE,ID INVOLUCRADO,COD_PLACA,ID_DOCUMENTO,FECHA_ACCIDENTE,HORA,DEPARTAMENTO,NOMBRE CARRETERA,CODIGO CARRETERA,KILOMETRO,MODALIDAD DE ACCIDENTE,HERIDOS,FALLECIDOS,LATITUD,LONGITUD
0,1,1,PLACA_1,DOCUMENTO_1,2016-01-06,13,AREQUIPA,C. PANAMERICANA SUR,PE1S,776,CHOQUE,0,0,-16.421327,-73.113400
1,1,2,PLACA_2,DOCUMENTO_2,2016-01-06,13,AREQUIPA,C. PANAMERICANA SUR,PE1S,776,CHOQUE,0,0,-16.421327,-73.113400
2,2,1,PLACA_3,DOCUMENTO_3,2016-01-09,7,HUANUCO,C. CENTRAL (HUANUCO-PASCO),PE3N,232,CHOQUE,28,1,-9.937104,-76.258587
3,2,2,PLACA_4,DOCUMENTO_4,2016-01-09,7,HUANUCO,C. CENTRAL (HUANUCO-PASCO),PE3N,232,CHOQUE,28,1,-9.937104,-76.258587
4,3,1,PLACA_5,DOCUMENTO_5,2016-01-09,1,AREQUIPA,C. AREQUIPA-PUNO,PE34A,167,CHOQUE,6,6,-15.828946,-71.081256

In [24]:
data_accidente.shape, data_accidente.groupby(by=['COD_PLACA']).size().shape

((1378, 15), (1297,))

In [26]:
data_accidente['DEPARTAMENTO'].value_counts()

LIMA             377
AREQUIPA         118
JUNIN            110
ANCASH            97
ICA               94
LA LIBERTAD       57
PUNO              49
CAJAMARCA         47
CUSCO             33
LAMBAYEQUE        29
APURIMAC          29
AYACUCHO          29
HUANUCO           27
HUANCAVELICA      22
-                 21
PIURA             19
SAN MARTIN        18
PASCO             17
AMAZONAS          15
TACNA             12
MOQUEGUA          11
MADRE DE DIOS      8
UCAYALI            4
JUNIN              2
CHICLAYO           2
LIMA               1
Name: DEPARTAMENTO, dtype: int64

In [17]:
data_accidente['MODALIDAD DE ACCIDENTE'].value_counts()

CHOQUE                1066
DESPISTE               204
ATROPELLO               41
ESPECIAL                31
CHOQUE                  11
VOLCADURA               10
INCENDIO                 7
DESPISTE/CHOQUE          2
NI                       2
DESPISTE/VOLCADURA       2
ATROPELLO                1
OTRO                     1
Name: MODALIDAD DE ACCIDENTE, dtype: int64

In [16]:
data_accidente.isnull().sum()

ID_ACCIDENTE                0
ID INVOLUCRADO              0
COD_PLACA                  20
ID_DOCUMENTO               46
FECHA_ACCIDENTE             0
HORA                        0
DEPARTAMENTO              130
NOMBRE CARRETERA            0
CODIGO CARRETERA           19
KILOMETRO                   0
MODALIDAD DE ACCIDENTE      0
HERIDOS                     0
FALLECIDOS                  0
LATITUD                   306
LONGITUD                  306
dtype: int64

In [27]:
data_accidente.columns

Index(['ID_ACCIDENTE', 'ID INVOLUCRADO', 'COD_PLACA', 'ID_DOCUMENTO',
       'FECHA_ACCIDENTE', 'HORA', 'DEPARTAMENTO', 'NOMBRE CARRETERA',
       'CODIGO CARRETERA', 'KILOMETRO', 'MODALIDAD DE ACCIDENTE', 'HERIDOS',
       'FALLECIDOS', 'LATITUD', 'LONGITUD'],
      dtype='object')

In [30]:
data_accidente[data_accidente['MODALIDAD DE ACCIDENTE'] == 'CHOQUE'].groupby(
    by=['DEPARTAMENTO', 'NOMBRE CARRETERA']
).size().sort_values()

DEPARTAMENTO  NOMBRE CARRETERA
TACNA         COSTANERA SUR                                              1
HUANUCO       C. HUANUCO-TINGO MARIA                                     2
JUNIN         C. MARGINAL TARMA - ACOBAMBA - LA MERCED  - LAS VEGAS      2
              C. LOS LIBERTADORES                                        2
              C. LA MERCED-TARMA                                         2
                                                                      ...
AREQUIPA      C. AREQUIPA - PUNO                                        48
LIMA          C. CENTRAL LIMA - LA OROYA                                55
ICA           C. PANAMERICANA SUR                                       69
LIMA          C. PANAMERICANA NORTE                                    118
              C. PANAMERICANA SUR                                      122
Length: 131, dtype: int64

In [33]:
data_pansur_choque = data_accidente[
    (data_accidente['MODALIDAD DE ACCIDENTE'] == 'CHOQUE') & (data_accidente['DEPARTAMENTO'] == 'LIMA') & (data_accidente['NOMBRE CARRETERA'] == 'C. PANAMERICANA SUR') 
]

data_pansur_choque.shape

(122, 15)

In [39]:
data_pansur_choque.head(50)

,ID_ACCIDENTE,ID INVOLUCRADO,COD_PLACA,ID_DOCUMENTO,FECHA_ACCIDENTE,HORA,DEPARTAMENTO,NOMBRE CARRETERA,CODIGO CARRETERA,KILOMETRO,MODALIDAD DE ACCIDENTE,HERIDOS,FALLECIDOS,LATITUD,LONGITUD
21,15,1,PLACA_22,DOCUMENTO_19,2016-01-23,5,LIMA,C. PANAMERICANA SUR,PE1S,152,CHOQUE,11,1,-13.169372,-76.358901
22,15,2,PLACA_23,DOCUMENTO_20,2016-01-23,5,LIMA,C. PANAMERICANA SUR,PE1S,152,CHOQUE,11,1,-13.169372,-76.358901
28,19,1,PLACA_29,DOCUMENTO_25,2016-01-30,9,LIMA,C. PANAMERICANA SUR,PE1S,56,CHOQUE,0,0,-12.450636,-76.755438
29,19,2,PLACA_30,DOCUMENTO_26,2016-01-30,9,LIMA,C. PANAMERICANA SUR,PE1S,56,CHOQUE,0,0,-12.450636,-76.755438
30,19,3,PLACA_31,DOCUMENTO_27,2016-01-30,9,LIMA,C. PANAMERICANA SUR,PE1S,56,CHOQUE,0,0,-12.450636,-76.755438
40,26,1,PLACA_41,NOSEENCONTRO,2016-02-11,23,LIMA,C. PANAMERICANA SUR,PE1S,74,CHOQUE,2,0,-12.583309,-76.672525
41,26,2,PLACA_42,NOSEENCONTRO,2016-02-11,23,LIMA,C. PANAMERICANA SUR,PE1S,74,CHOQUE,2,0,-12.583309,-76.672525
58,34,1,PLACA_59,DOCUMENTO_45,2016-02-19,14,LIMA,C. PANAMERICANA SUR,PE1S,61,CHOQUE,0,0,-12.494298,-76.743570
59,34,2,PLACA_60,NOSEENCONTRO,2016-02-19,14,LIMA,C. PANAMERICANA SUR,PE1S,61,CHOQUE,0,0,-12.494298,-76.743570
67,38,1,PLACA_68,DOCUMENTO_51,2016-02-20,17,LIMA,C. PANAMERICANA SUR,PE1S,31,CHOQUE,4,0,-12.280984,-76.882232
68,38,2,PLACA_69,DOCUMENTO_52,2016-02-20,17,LIMA,C. PANAMERICANA SUR,PE1S,31,CHOQUE,4,0,-12.280984,-76.882232
69,38,3,PLACA_70,DOCUMENTO_53,2016-02-20,17,LIMA,C. PANAMERICANA SUR,PE1S,31,CHOQUE,4,0,-12.280984,-76.882232
70,38,4,PLACA_71,DOCUMENTO_54,2016-02-20,17,LIMA,C. PANAMERICANA SUR,PE1S,31,CHOQUE,4,0,-12.280984,-76.882232
89,49,1,PLACA_89,DOCUMENTO_68,2016-03-12,12,LIMA,C. PANAMERICANA SUR,PE1S,55,CHOQUE,0,0,-12.441819,-76.756839
90,49,2,PLACA_90,DOCUMENTO_69,2016-03-12,12,LIMA,C. PANAMERICANA SUR,PE1S,55,CHOQUE,0,0,-12.441819,-76.756839
91,49,3,PLACA_91,DOCUMENTO_70,2016-03-12,12,LIMA,C. PANAMERICANA SUR,PE1S,55,CHOQUE,0,0,-12.441819,-76.756839
95,53,1,PLACA_95,DOCUMENTO_73,2016-03-21,5,LIMA,C. PANAMERICANA SUR,PE1S,22,CHOQUE,2,0,-12.238162,-76.952434
96,53,2,PLACA_96,DOCUMENTO_74,2016-03-21,5,LIMA,C. PANAMERICANA SUR,PE1S,22,CHOQUE,2,0,-12.238162,-76.952434
111,62,1,PLACA_111,DOCUMENTO_86,2016-04-09,20,LIMA,C. PANAMERICANA SUR,PE1S,43,CHOQUE,1,0,-12.353192,-76.803527
112,62,2,PLACA_112,DOCUMENTO_87,2016-04-09,20,LIMA,C. PANAMERICANA SUR,PE1S,43,CHOQUE,1,0,-12.353192,-76.803527
125,69,1,PLACA_125,DOCUMENTO_96,2016-04-19,21,LIMA,C. PANAMERICANA SUR,PE1S,59,CHOQUE,0,0,-12.476840,-76.748346
126,69,2,PLACA_126,DOCUMENTO_97,2016-04-19,21,LIMA,C. PANAMERICANA SUR,PE1S,59,CHOQUE,0,0,-12.476840,-76.748346
136,75,1,PLACA_135,DOCUMENTO_105,2016-04-30,18,LIMA,C. PANAMERICANA SUR,PE1S,35,CHOQUE,0,0,-12.299403,-76.850670
137,75,2,PLACA_136,DOCUMENTO_106,2016-04-30,18,LIMA,C. PANAMERICANA SUR,PE1S,35,CHOQUE,0,0,-12.299403,-76.850670
138,76,1,PLACA_137,DOCUMENTO_107,2016-05-02,14,LIMA,C. PANAMERICANA SUR,PE1S,172,CHOQUE,1,0,-13.304802,-76.253912
139,76,2,PLACA_138,DOCUMENTO_108,2016-05-02,14,LIMA,C. PANAMERICANA SUR,PE1S,172,CHOQUE,1,0,-13.304802,-76.253912
176,98,1,PLACA_174,DOCUMENTO_141,2016-06-06,11,LIMA,C. PANAMERICANA SUR,PE1S,34,CHOQUE,8,0,-12.295563,-76.858986
177,98,2,PLACA_175,DOCUMENTO_142,2016-06-06,11,LIMA,C. PANAMERICANA SUR,PE1S,34,CHOQUE,8,0,-12.295563,-76.858986
209,120,1,PLACA_207,DOCUMENTO_167,2016-07-11,20,LIMA,C. PANAMERICANA SUR,PE1S,74.5,CHOQUE,15,0,-12.583309,-76.672525
210,120,2,PLACA_208,DOCUMENTO_168,2016-07-11,20,LIMA,C. PANAMERICANA SUR,PE1S,74.5,CHOQUE,15,0,-12.583309,-76.672525
217,124,1,PLACA_215,DOCUMENTO_174,2016-07-18,22,LIMA,C. PANAMERICANA SUR,PE1S,76,CHOQUE,0,0,-12.596456,-76.662424
218,124,2,PLACA_216,DOCUMENTO_175,2016-07-18,22,LIMA,C. PANAMERICANA SUR,PE1S,76,CHOQUE,0,0,-12.596456,-76.662424
228,130,1,PLACA_225,DOCUMENTO_182,2016-07-28,6,LIMA,C. PANAMERICANA SUR,PE1S,127,CHOQUE,0,0,-12.991233,-76.488963
229,130,2,PLACA_226,DOCUMENTO_183,2016-07-28,6,LIMA,C. PANAMERICANA SUR,PE1S,127,CHOQUE,0,0,NaN,NaN
299,169,1,PLACA_290,DOCUMENTO_241,2016-09-15,19,LIMA,C. PANAMERICANA SUR,PE1S,99.8,CHOQUE,6,0,-12.777310,-76.586805
300,169,2,PLACA_291,NOINDICA,2016-09-15,19,LIMA,C. PANAMERICANA SUR,PE1S,99.8,CHOQUE,6,0,-12.777310,-76.586805
422,239,1,PLACA_406,DOCUMENTO_321,2017-01-03,07:10:00,LIMA,C. PANAMERICANA SUR,PE1S,93+500,CHOQUE,0,0,-12.731922,-76.615420
423,239,2,PLACA_407,DOCUMENTO_322,2017-01-03,07:10:00,LIMA,C. PANAMERICANA SUR,PE1S,93+500,CHOQUE,0,0,-12.731922,-76.615420
445,253,1,PLACA_426,DOCUMENTO_340,2017-01-13,00:05:00,LIMA,C. PANAMERICANA SUR,PE1S,91+500,CHOQUE,0,0,-12.716870,-76.624615
446,253,2,PLACA_427,DOCUMENTO_341,2017-01-13,00:05:00,LIMA,C. PANAMERICANA SUR,PE1S,91+500,CHOQUE,0,0,-12.716870,-76.624615
451,256,1,PLACA_431,DOCUMENTO_345,2017-01-14,16:00:00,LIMA,C. PANAMERICANA SUR,PE1S,44+700,CHOQUE,0,0,-12.359522,-76.796964
452,256,2,PLACA_432,DOCUMENTO_346,2017-01-14,16:00:00,LIMA,C. PANAMERICANA SUR,PE1S,44+700,CHOQUE,0,0,-12.359522,-76.796964
453,256,3,PLACA_433,DOCUMENTO_347,2017-01-14,16:00:00,LIMA,C. PANAMERICANA SUR,PE1S,44+700,CHOQUE,0,0,-12.359522,-76.796964
454,257,1,PLACA_434,DOCUMENTO_348,2017-01-14,00:30:00,LIMA,C. PANAMERICANA SUR,PE1S,151+000,CHOQUE,0,0,-13.163575,-76.365975
455,257,2,PLACA_295,DOCUMENTO_349,2017-01-14,00:30:00,LIMA,C. PANAMERICANA SUR,PE1S,151+000,CHOQUE,0,0,-13.163575,-76.365975
456,258,1,PLACA_435,DOCUMENTO_350,2017-01-16,01:55:00,LIMA,C. PANAMERICANA SUR,PE1S,82+000,CHOQUE,10,1,-12.648449,-76.666004
457,258,2,PLACA_436,DOCUMENTO_351,2017-01-16,01:55:00,LIMA,C. PANAMERICANA SUR,PE1S,82+000,CHOQUE,10,1,-12.648449,-76.666004
458,258,3,PLACA_437,NaN,2017-01-16,01:55:00,LIMA,C. PANAMERICANA SUR,PE1S,82+000,CHOQUE,10,1,-12.648449,-76.666004
531,294,1,PLACA_509,NOIDENTIFICADO,2017-02-27,11:30:00,LIMA,C. PANAMERICANA SUR,PE1S,63+000,CHOQUE,0,0,-12.510417,-76.735715
532,294,2,PLACA_510,NOIDENTIFICADO,2017-02-27,11:30:00,LIMA,C. PANAMERICANA SUR,PE1S,63+000,CHOQUE,0,0,-12.510417,-76.735715

In [42]:
list_placas_pan_sur = pd.DataFrame(data_pansur_choque['COD_PLACA'])
list_placas_pan_sur

       COD_PLACA
21      PLACA_22
22      PLACA_23
28      PLACA_29
29      PLACA_30
30      PLACA_31
...          ...
1353  PLACA_1273
1354  PLACA_1274
1368  PLACA_1287
1369  PLACA_1288
1370  PLACA_1289

[122 rows x 1 columns]

In [40]:
data_gps = pd.read_csv("{}/DATA_GPS_2016_2018_HACKATON.csv".format(subfolder))
data_gps.head(50)

    COD_PLACA       FECHA      HORA    LATITUD   LONGITUD VELOCIDAD
0   PLACA_205  01/07/2016  22:28:12 -13.337239 -74.585337        59
1   PLACA_205  01/07/2016  00:04:09 -13.655298 -76.150967        54
2   PLACA_205  01/07/2016  07:36:05 -13.133835 -74.230573         0
3   PLACA_205  01/07/2016  06:38:57 -13.144506 -74.229375        27
4   PLACA_205  01/07/2016  02:15:09 -13.598481 -75.356658        44
5   PLACA_205  01/07/2016  22:55:52 -13.360487 -74.737574        45
6   PLACA_205  01/07/2016  20:14:26 -13.134119 -74.230322         0
7   PLACA_205  01/07/2016  02:34:09 -13.607675 -75.321516        42
8   PLACA_205  01/07/2016  09:25:45 -13.135333 -74.230811         0
9   PLACA_205  01/07/2016  00:01:30 -13.627882 -76.152081        81
10  PLACA_205  01/07/2016  04:28:31 -13.360006 -74.804381        51
11  PLACA_205  01/07/2016  07:47:11 -13.133882 -74.230534         0
12  PLACA_205  01/07/2016  19:22:22 -13.133936 -74.230107         1
13  PLACA_205  01/07/2016  21:19:12 -13.210623 -74.273167        11
14  PLACA_205  01/07/2016  07:07:30 -13.133931 -74.230536         0
15  PLACA_205  01/07/2016  19:57:41 -13.133915 -74.230265         0
16  PLACA_205  01/07/2016  07:31:13 -13.133792 -74.230564         0
17  PLACA_205  01/07/2016  20:42:12 -13.134947 -74.229581        11
18  PLACA_205  01/07/2016  06:54:10 -13.134160 -74.230403         0
19  PLACA_205  01/07/2016  09:52:09 -13.135299 -74.230768         0
20  PLACA_205  01/07/2016  10:48:59 -13.135187 -74.230336         0
21  PLACA_205  01/07/2016  09:42:45 -13.135293 -74.230798         0
22  PLACA_205  01/07/2016  21:14:12 -13.206258 -74.272356         0
23  PLACA_205  01/07/2016  02:38:09 -13.596281 -75.309153        41
24  PLACA_205  01/07/2016  11:56:08 -13.135200 -74.230277         0
25  PLACA_205  01/07/2016  14:17:28 -13.135377 -74.227284         0
26  PLACA_205  01/07/2016  16:58:32 -13.134988 -74.228394         0
27  PLACA_205  01/07/2016  22:52:52 -13.352108 -74.726183        46
28  PLACA_205  01/07/2016  04:27:31 -13.359493 -74.814395        72
29  PLACA_205  01/07/2016  17:10:43 -13.133953 -74.230106         0
30  PLACA_205  01/07/2016  07:32:26 -13.133926 -74.230530         0
31  PLACA_205  01/07/2016  16:11:56 -13.135406 -74.227506         6
32  PLACA_205  01/07/2016  22:10:39 -13.349661 -74.464783        93
33  PLACA_205  01/07/2016  05:14:03 -13.349504 -74.473471        84
34  PLACA_205  01/07/2016  02:06:09 -13.608006 -75.384754        43
35  PLACA_205  01/07/2016  00:02:33 -13.640753 -76.152903        86
36  PLACA_205  01/07/2016  16:59:04 -13.135029 -74.228293         8
37  PLACA_205  01/07/2016  09:39:44 -13.135274 -74.230771         0
38  PLACA_205  01/07/2016  16:26:36 -13.135041 -74.228419         0
39  PLACA_205  01/07/2016  06:52:38 -13.134117 -74.230383         0
40  PLACA_205  01/07/2016  20:15:53 -13.134188 -74.230380         0
41  PLACA_205  01/07/2016  05:06:03 -13.341325 -74.538762        66
42  PLACA_205  01/07/2016  07:22:11 -13.133911 -74.230565         0
43  PLACA_205  01/07/2016  10:05:58 -13.135293 -74.230741         0
44  PLACA_205  01/07/2016  05:08:03 -13.342076 -74.521093        64
45  PLACA_205  01/07/2016  04:43:42 -13.354687 -74.723841        50
46  PLACA_205  01/07/2016  07:47:31 -13.133834 -74.230551         0
47  PLACA_205  01/07/2016  04:45:42 -13.360884 -74.709534        55
48  PLACA_205  01/07/2016  07:59:17 -13.134025 -74.230575         0
49  PLACA_205  01/07/2016  23:07:52 -13.360258 -74.801949        58

In [6]:
data_gps.shape

(18126919, 6)

In [8]:
data_gps.groupby(by=['COD_PLACA']).size().sort_values()

COD_PLACA
PLACA_76           1
PLACA_1010         3
PLACA_78           9
PLACA_37          11
PLACA_1008        19
               ...
PLACA_749     161460
PLACA_1274    177796
PLACA_406     215463
PLACA_133     223881
PLACA_823     228712
Length: 699, dtype: int64

In [9]:
data_gps[data_gps['COD_PLACA'] == 'PLACA_749']

         COD_PLACA       FECHA      HORA    LATITUD   LONGITUD VELOCIDAD
9785984  PLACA_749  25/09/2017  00:14:29 -12.073885 -77.014575         0
9785985  PLACA_749  25/09/2017  02:14:29 -12.073885 -77.014575         0
9785986  PLACA_749  25/09/2017  02:48:37 -12.073885 -77.014575         0
9785987  PLACA_749  25/09/2017  02:48:38 -12.073885 -77.014575         0
9785988  PLACA_749  25/09/2017  03:00:30 -12.073885 -77.014575         0
...            ...         ...       ...        ...        ...       ...
9947439  PLACA_749  25/10/2017  23:55:52 -12.073890 -77.014660         0
9947440  PLACA_749  25/10/2017  23:56:52 -12.073890 -77.014660         0
9947441  PLACA_749  25/10/2017  23:57:52 -12.073890 -77.014660         0
9947442  PLACA_749  25/10/2017  23:58:52 -12.073890 -77.014660         0
9947443  PLACA_749  25/10/2017  23:59:52 -12.073890 -77.014660         0

[161460 rows x 6 columns]